# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: In the Garage
email: sannielee@gmail.com
description: # this means to ignore newlines until "baseurl:"
  Thoughts on tech, women in tech, pop culture, and living abroad in Germany and China.
title_image: 'https://sannielee.com/img/assets/rocknroll.jpg'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://sannielee.com/' # the base hostname & protocol for your site
twitter_username: geekrockchick24
github_username:  psannielee

twitter:
    username: geekrockchick24
    card: summary    

plugins: 
- jekyll-paginate
- jekyll-seo-tag


# Build settings
highlighter: rouge
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
   
social:
    github: psannielee
    twitter: geekrockchick24
    name: Patricia Sannie Lee
    linkedin: psannielee
    facebook: psannielee
    google+: https://plus.google.com/u/0/+PatriciaLee2007
    
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME