# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: In the Garage
email: sannielee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on tech, women in tech, pop culture, and living abroad in Germany and China.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://sannielee.com" # the base hostname & protocol for your site
twitter_username: geekrockchick24
github_username:  psannielee

plugins: 
- jekyll-paginate


# Build settings
highlighter: rouge
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
   
social:
    github: psannielee
    twitter: geekrockchick24
    
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME